# Generated by Django 3.0.8 on 2021-03-23 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_truck'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Truck',
        ),
    ]
