# Generated by Django 3.0.8 on 2021-03-22 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('branch', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmployeeProfile',
            new_name='BranchProfile',
        ),
    ]
