# Generated by Django 3.0.8 on 2021-03-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0002_auto_20210322_2300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='branch.BranchProfile')),
            ],
        ),
    ]
