# Generated by Django 3.0.8 on 2021-03-23 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0004_auto_20210323_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='in_use',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('space', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=50)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_to', to='branch.BranchProfile')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips_from', to='branch.BranchProfile')),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='truck_trips', to='branch.Truck')),
            ],
        ),
    ]
